# Generated by Django 4.2.4 on 2023-10-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='img',
            field=models.ImageField(upload_to='avatar/'),
        ),
    ]
