# Generated by Django 4.2.4 on 2023-10-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='img',
            field=models.ImageField(blank=True, default='Avatar/user.png', null=True, upload_to='Avatar/'),
        ),
    ]
